version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/templates-certbot/certbot.conf.template:/etc/nginx/templates/default.conf.template
      - ./.etc/letsencrypt:/etc/letsencrypt
      - ./.docker/certbot/data:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --webroot --webroot-path=/var/www/certbot
      --email ${USER_EMAIL} --server https://acme-staging-v02.api.letsencrypt.org/directory --agree-tos --no-eff-email --test-cert
      -d ${APP_DOMAIN}
    volumes:
      - ./.etc/letsencrypt:/etc/letsencrypt
      - ./.docker/certbot/data:/var/www/certbot